apiVersion: v1
kind: Service
metadata:
  name: noticia-da-hora-service
spec:
  selector:
    app: noticia-da-hora
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
